# permissions for end users to view obmreplicas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: obmreplica-viewer-role
rules:
- apiGroups:
  - obm.obm.datacommand
  resources:
  - obmreplicas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - obm.obm.datacommand
  resources:
  - obmreplicas/status
  verbs:
  - get
