---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - obm.obm.datacommand
  resources:
  - obmreplicas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - obm.obm.datacommand
  resources:
  - obmreplicas/finalizers
  verbs:
  - update
- apiGroups:
  - obm.obm.datacommand
  resources:
  - obmreplicas/status
  verbs:
  - get
  - patch
  - update
